Lab6/CokingPlace/CokingPlace/Controllers/HomeController.cs
using CokingPlace.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CokingPlace.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            CookingBookDbContext db = new CookingBookDbContext();
            try
            {
                ViewBag.LastRecipes = db.Recipes.OrderBy(i => i.CreationDate).Take(9).ToList();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lab6/CokingPlace/CokingPlace/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CokingPlace.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Drawing;
using System.Web.Security;

namespace CokingPlace.Controllers
{
    public class RecipesController : Controller
    {
        private CookingBookDbContext db = new CookingBookDbContext();

        public ActionResult Index(int categoryId = 0, string search = "")
        {
            List<Recipe> list;

            if (categoryId == 0 && string.IsNullOrEmpty(search))
            {
                return View(db.Recipes.ToList()) ;
            }

            if (!string.IsNullOrEmpty(search))
            {
                list = db.Recipes.Where(x => x.Name.Contains(search)).ToList();
            }
            else
            {
                ViewBag.PageHeader = db.Categories.Single(x => x.Id == categoryId).Name;
                list = db.Recipes.Where(x => x.CategoryId == categoryId).ToList();
            }
            return View(list);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }

            ViewBag.IsAuthor = User.Identity.GetUserId() == recipe.UserId;

            return View(recipe);
        }

        [Authorize]
        public ActionResult Create()
        {
            SetCategoriesViewBag();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Recipe recipe, string categories, HttpPostedFileBase uploadImage)
        {
            if (ModelState.IsValid)
            {

                recipe.CreationDate = DateTime.Today;
                recipe.UserId = User.Identity.GetUserId();
                recipe.UserName = User.Identity.Name;

                SetPicture(recipe, uploadImage);

                int categoryId;

                if (!int.TryParse(categories, out categoryId))
                {
                    recipe.CategoryId = 1;
                }
                else recipe.CategoryId = categoryId;

                db.Recipes.Add(recipe);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(recipe);
        }

        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Recipe recipe = db.Recipes.Find(id);

            if (recipe == null)
            {
                return HttpNotFound();
            }

            SetCategoriesViewBag();

            return View(recipe);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Recipe recipe, HttpPostedFileBase uploadImage)
        {
            if (ModelState.IsValid)
            {
                if (uploadImage != null)
                    SetPicture(recipe, uploadImage);
                db.Entry(recipe).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(recipe);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View(recipe);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Recipe recipe = db.Recipes.Find(id);
            db.Recipes.Remove(recipe);
            db.SaveChanges();
            DeleteOldPicture(recipe.ImageUrl);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private void SetCategoriesViewBag()
        {
            var categories = new List<SelectListItem>();

            foreach (var item in db.Categories)
            {
                categories.Add(new SelectListItem
                { Text = item.Name, Value = item.Id.ToString() });
            }

            ViewBag.categories = categories;
        }

        private void SetPicture(Recipe recipe, HttpPostedFileBase uploadImage)
        {
            if (!string.IsNullOrEmpty(recipe.ImageUrl))
                DeleteOldPicture(recipe.ImageUrl);

            string fileName = "", uploadUrl, serverUrl;
            serverUrl = "~/Content/Images/RecipeImages";
            uploadUrl = Server.MapPath(serverUrl);

            try
            {
                using (var bitmap = new Bitmap(uploadImage.InputStream))
                {
                    fileName = Guid.NewGuid().ToString() + Path.GetExtension(uploadImage.FileName);
                }
            }
            catch
            {
                fileName = "noimage.png";
                return;
            }
            finally
            {
                recipe.ImageUrl = Path.Combine(serverUrl, fileName);
            }

            uploadImage.SaveAs(Path.Combine(uploadUrl, fileName));
        }

        private void DeleteOldPicture(string url)
        {
            url = Server.MapPath(url);

            if ((System.IO.File.Exists(url)))
            {
                System.IO.File.Delete(url);
            }
        }
    }
}

Lab6/CokingPlace/CokingPlace/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Lab6/CokingPlace/CokingPlace/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Lab6/CokingPlace/CokingPlace/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@using CokingPlace.Models;

<div class="jumbotron">
    <div class="row">
        <h1 class="shadow-text">Cooking place</h1>
        @if (Request.IsAuthenticated)
        {
            @Html.ActionLink("Додати рецепт", "Create", "Recipes", null, new { @class = "col-md-2 btn btn-default" })
        }
    </div>
</div>

<h3>Нові рецепти</h3>
<div class="col-xs-12">

    <div id="myCarousel" class="carousel slide">
        <div class="carousel-inner">
            @{
                var list = ViewBag.LastRecipes as List<Recipe>;
                string attr;
                for (int i = 0; i < list.Count; i++)
                {
                    if (i == 0)
                    {
                        attr = "active";
                    }
                    else { attr = ""; }
                    <div class="item @attr">
                        <div class="row">
                            @for (int j = 0; j < 3; j++, i++)
                            {
                                <div class="col-xs-4">
                                    <a href="@Url.Action("Details", "Recipes", new { id = list.ElementAt(i).Id })" class="thumbnail">
                                        <img src="@Url.Content(list.ElementAt(i).ImageUrl)" alt="Image" class="img-responsive">
                                    </a>
                                </div>
                            }
                        </div>
                    </div>
                }
            }
        </div>

        <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>

        <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
    </div>
</div>